package review_test

import (
	"strings"
	"testing"

	"github.com/probertson/diff-by-numbers/internal/review"
)

// ackRow is one rendered row of an expansion, reduced to what a unified diff is
// judged by: which side it is on, its number, and whether it changed.
type ackRow struct {
	side    review.Side
	number  int
	changed bool
}

func rowsOf(view review.ExcerptView) []ackRow {
	rows := make([]ackRow, len(view.Lines))
	for i, line := range view.Lines {
		rows[i] = ackRow{line.Side, line.Number, line.Changed}
	}
	return rows
}

func assertRows(t *testing.T, got, want []ackRow) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("expected %d rows %+v, got %d %+v", len(want), want, len(got), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("row %d: expected %+v, got %+v", i, want[i], got[i])
		}
	}
}

// acknowledgedEdits is a session whose one Step acknowledges mod.ts, which git saw
// as two edits: old line 2 replaced by new lines 2-3, then old lines 9-10 removed
// outright.
func acknowledgedEdits(t *testing.T) *review.Session {
	t.Helper()
	deriver := pairingDeriver{
		lines: []review.ChangedLine{
			{File: "mod.ts", Side: review.OldSide, Line: 2},
			{File: "mod.ts", Side: review.NewSide, Line: 2},
			{File: "mod.ts", Side: review.NewSide, Line: 3},
			{File: "mod.ts", Side: review.OldSide, Line: 9},
			{File: "mod.ts", Side: review.OldSide, Line: 10},
		},
		correspondences: []review.Correspondence{
			{File: "mod.ts", OldFirst: 2, OldLast: 2, NewFirst: 2, NewLast: 3},
			{File: "mod.ts", OldFirst: 9, OldLast: 10},
		},
	}
	session := review.NewSession(sideResolver{}, deriver)
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{acknowledgingStep("mod.ts")}
	mustPost(t, session, walkthrough)
	mustAdvance(t, session)
	return session
}

func TestAnExpandedEditReadsAsAUnifiedDiff(t *testing.T) {
	session := acknowledgedEdits(t)

	views, err := session.ExpandAcknowledgement(1, 0)

	if err != nil {
		t.Fatalf("expected expansion to succeed, got %v", err)
	}
	if len(views) != 2 {
		t.Fatalf("expected one Excerpt per edit, got %d: %+v", len(views), views)
	}
	assertRows(t, rowsOf(views[0]), []ackRow{
		{review.OldSide, 2, true}, // the before it replaced, just above
		{review.NewSide, 2, true},
		{review.NewSide, 3, true},
	})
	// A pure removal has no after-side to sit beside, so it stays before-only — in
	// file order, after the edit above it.
	assertRows(t, rowsOf(views[1]), []ackRow{
		{review.OldSide, 9, true},
		{review.OldSide, 10, true},
	})
}

func TestAnAnchorCanPointIntoAcknowledgedCode(t *testing.T) {
	session := acknowledgedEdits(t)
	ack := 0
	target := review.AnchorTarget{
		Acknowledgement: &ack,
		ExcerptIndex:    0,
		Start:           oldRow(2),
		End:             newRow(3),
	}

	anchor, err := session.Anchor(target)

	if err != nil {
		t.Fatalf("expected an Anchor into acknowledged code, got %v", err)
	}
	if anchor.File != "mod.ts" || len(anchor.Lines) != 3 {
		t.Fatalf("expected the 3 rows of mod.ts's first edit, got %s with %d lines", anchor.File, len(anchor.Lines))
	}
	rendered := anchor.Render()
	// The Anchor must tell the agent it is disputing a "mechanical" claim, not
	// just pointing at a line.
	want := `acknowledged in Step "Mechanical" (mechanical: regenerated by the build)`
	if !strings.Contains(rendered, want) {
		t.Errorf("expected the rendered Anchor to contain %q\n---\n%s", want, rendered)
	}
}

func TestAnAnchorIntoNarratedCodeDoesNotClaimAnAcknowledgement(t *testing.T) {
	session := newSession()
	mustPost(t, session, validWalkthrough())
	mustAdvance(t, session)

	anchor, err := session.Anchor(span(0, 20, 22))

	if err != nil {
		t.Fatalf("expected an Anchor, got %v", err)
	}
	if strings.Contains(anchor.Render(), "acknowledged") {
		t.Errorf("expected narrated code not to read as acknowledged:\n%s", anchor.Render())
	}
}

func TestAnchoringAnAcknowledgementTheStepLacksIsRejected(t *testing.T) {
	session := acknowledgedEdits(t)
	ack := 4

	_, err := session.Anchor(review.AnchorTarget{Acknowledgement: &ack, Start: newRow(2), End: newRow(2)})

	assertRejected(t, err, review.RejectedBadSelection)
}

func TestAnchoringAnAcknowledgedOpaqueChangeIsRejected(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{acknowledgingStep("logo.png")}
	session := sessionDerivingBoth(nil, []review.OpaqueChange{{File: "logo.png", Kind: review.OpaqueBinary, Detail: "binary file"}})
	mustPost(t, session, walkthrough)
	mustAdvance(t, session)
	ack := 0

	_, err := session.Anchor(review.AnchorTarget{Acknowledgement: &ack, Start: newRow(1), End: newRow(1)})

	assertRejected(t, err, review.RejectedBadSelection)
}

func TestAnAnchorRemembersWhichAcknowledgementItLiesIn(t *testing.T) {
	session := acknowledgedEdits(t)
	ack := 0

	anchor, err := session.Anchor(review.AnchorTarget{Acknowledgement: &ack, Start: newRow(2), End: newRow(3)})

	if err != nil {
		t.Fatal(err)
	}
	if anchor.Acknowledgement == nil || *anchor.Acknowledgement != 0 {
		t.Errorf("expected the Anchor to record Acknowledgement 0, got %v", anchor.Acknowledgement)
	}
}
