package review_test

import (
	"testing"

	"github.com/probertson/diff-by-numbers/internal/review"
)

func sessionDerivingBoth(lines []review.ChangedLine, opaque []review.OpaqueChange) *review.Session {
	return review.NewSession(stubResolver{}, fixedDeriver{lines: lines, opaque: opaque})
}

func acknowledgingStep(files ...string) review.Step {
	return review.Step{
		Name:        "Mechanical",
		Explanation: "regenerated and swapped, nothing to read line by line",
		Acknowledgements: []review.Acknowledgement{
			{Repository: "/repos/argus-portal", Files: files, Reason: "mechanical: regenerated by the build"},
		},
	}
}

func ackEntry(view review.AcknowledgementView, file string) (review.AcknowledgedFile, bool) {
	for _, entry := range view.Entries {
		if entry.File == file {
			return entry, true
		}
	}
	return review.AcknowledgedFile{}, false
}

func containsInt(haystack []int, needle int) bool {
	for _, n := range haystack {
		if n == needle {
			return true
		}
	}
	return false
}

func TestAnAcknowledgementCoversChangedLinesInPlaceOfAnExcerpt(t *testing.T) {
	walkthrough := validWalkthrough()
	// A regenerated lockfile: 500 changed lines, none of which should be read.
	walkthrough.Steps = []review.Step{acknowledgingStep("package-lock.json")}
	session := sessionDerivingBoth(changed("package-lock.json", 1, 500), nil)

	err := session.Post(walkthrough)

	if err != nil {
		t.Fatalf("expected an acknowledged lockfile to be accepted, got %v", err)
	}
}

func TestAnAcknowledgedBulkOfLinesDoesNotTripTheBudget(t *testing.T) {
	walkthrough := validWalkthrough()
	// Far over the 30-line budget, but acknowledged, so nothing is "shown".
	walkthrough.Steps = []review.Step{acknowledgingStep("package-lock.json")}
	session := sessionDerivingBoth(changed("package-lock.json", 1, 200), nil)

	if err := session.Post(walkthrough); err != nil {
		t.Fatalf("expected acknowledged lines to be free of the budget, got %v", err)
	}
}

func TestAnOpaqueChangeIsCoveredByAnAcknowledgement(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{acknowledgingStep("logo.png")}
	session := sessionDerivingBoth(nil, []review.OpaqueChange{{File: "logo.png", Kind: review.OpaqueBinary}})

	if err := session.Post(walkthrough); err != nil {
		t.Fatalf("expected an acknowledged binary to be accepted, got %v", err)
	}
}

func TestAnUnaccountedOpaqueChangeIsRejectedNamingIt(t *testing.T) {
	// The Walkthrough covers src/fetch.ts by Excerpt, but nothing accounts for the binary.
	session := sessionDerivingBoth(changed("src/fetch.ts", 20, 22),
		[]review.OpaqueChange{{File: "logo.png", Kind: review.OpaqueBinary}})

	err := session.Post(validWalkthrough())

	assertRejected(t, err, review.RejectedUncoveredChanges)
	assertDetailContains(t, err, "logo.png")
}

func TestAcknowledgingAFileWithNoChangesIsRejected(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = append(walkthrough.Steps, acknowledgingStep("unchanged.ts"))
	session := sessionDeriving(changed("src/fetch.ts", 20, 22))

	err := session.Post(walkthrough)

	assertRejected(t, err, review.RejectedEmptyAcknowledgement)
	assertDetailContains(t, err, "unchanged.ts")
}

func TestAStepWithNeitherExcerptNorAcknowledgementIsRejected(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps[0].Excerpts = nil

	err := newSession().Post(walkthrough)

	assertRejected(t, err, review.RejectedMalformedStep)
}

func TestAnAcknowledgementWithoutAReasonIsRejected(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps[0].Acknowledgements = []review.Acknowledgement{
		{Repository: "/repos/argus-portal", Files: []string{"package-lock.json"}},
	}

	err := newSession().Post(walkthrough)

	assertRejected(t, err, review.RejectedMalformedStep)
}

func TestAnAcknowledgementForAnUnknownRepositoryIsRejected(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps[0].Acknowledgements = []review.Acknowledgement{
		{Repository: "/repos/not-in-set", Files: []string{"x.ts"}, Reason: "mechanical"},
	}

	err := newSession().Post(walkthrough)

	assertRejected(t, err, review.RejectedMalformedStep)
}

func TestCoverageCountsOpaqueAndAcknowledgedChanges(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{
		{
			Name: "The code", Explanation: "the real change",
			Excerpts: []review.Excerpt{{Repository: "/repos/argus-portal", File: "a.ts", Side: review.NewSide, FirstLine: 1, LastLine: 10}},
		},
		acknowledgingStep("package-lock.json", "logo.png"),
	}
	lines := append(changed("a.ts", 1, 3), changed("package-lock.json", 1, 4)...) // 3 code + 4 lockfile
	opaque := []review.OpaqueChange{{File: "logo.png", Kind: review.OpaqueBinary}}
	session := sessionDerivingBoth(lines, opaque)
	mustPost(t, session, walkthrough)

	if got := session.View().Coverage.Total; got != 8 {
		t.Fatalf("expected total 8 (3 code + 4 lockfile + 1 binary), got %d", got)
	}

	mustAdvance(t, session)
	if got := session.View().Coverage.Seen; got != 3 {
		t.Errorf("after the code Step expected 3 seen, got %d", got)
	}

	mustAdvance(t, session)
	if got := session.View().Coverage.Seen; got != 8 {
		t.Errorf("after the acknowledgement Step expected all 8 seen, got %d", got)
	}
}

func TestAnAcknowledgementRendersAsAManifestOfFilesAndCounts(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{acknowledgingStep("package-lock.json", "logo.png")}
	lines := changed("package-lock.json", 1, 40)
	opaque := []review.OpaqueChange{{File: "logo.png", Kind: review.OpaqueBinary, Detail: "binary file"}}
	session := sessionDerivingBoth(lines, opaque)
	mustPost(t, session, walkthrough)
	mustAdvance(t, session)

	step := session.View().Step
	if step == nil || len(step.Acknowledgements) != 1 {
		t.Fatalf("expected one Acknowledgement in the Step view, got %+v", step)
	}
	ack := step.Acknowledgements[0]
	if ack.Reason == "" {
		t.Error("expected the manifest to carry the Acknowledgement's reason")
	}

	lock, ok := ackEntry(ack, "package-lock.json")
	if !ok || lock.ChangedLines != 40 {
		t.Errorf("expected package-lock.json with 40 changed lines, got %+v (found=%v)", lock, ok)
	}
	logo, ok := ackEntry(ack, "logo.png")
	if !ok || logo.Opaque != review.OpaqueBinary {
		t.Errorf("expected logo.png as a binary Opaque Change, got %+v (found=%v)", logo, ok)
	}
}

func TestManifestClassifiesWhatChangedPerFile(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{acknowledgingStep("mod.ts", "new.ts", "gone.ts", "logo.png")}
	lines := []review.ChangedLine{
		{File: "mod.ts", Side: review.OldSide, Line: 1},
		{File: "mod.ts", Side: review.NewSide, Line: 1},
		{File: "new.ts", Side: review.NewSide, Line: 1},
		{File: "new.ts", Side: review.NewSide, Line: 2},
		{File: "gone.ts", Side: review.OldSide, Line: 1},
		{File: "gone.ts", Side: review.OldSide, Line: 2},
	}
	opaque := []review.OpaqueChange{{File: "logo.png", Kind: review.OpaqueBinary}}
	session := sessionDerivingBoth(lines, opaque)
	mustPost(t, session, walkthrough)
	mustAdvance(t, session)

	ack := session.View().Step.Acknowledgements[0]
	want := map[string]string{
		"mod.ts":   review.ChangeModified,
		"new.ts":   review.ChangeAdded,
		"gone.ts":  review.ChangeRemoved,
		"logo.png": string(review.OpaqueBinary),
	}
	for file, expected := range want {
		entry, ok := ackEntry(ack, file)
		if !ok || entry.Change != expected {
			t.Errorf("expected %s classified as %q, got %q (found=%v)", file, expected, entry.Change, ok)
		}
	}
}

func TestAnAcknowledgementExpandsIntoRealExcerpts(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{acknowledgingStep("package-lock.json")}
	session := sessionDerivingBoth(changed("package-lock.json", 5, 9), nil)
	mustPost(t, session, walkthrough)

	views, err := session.ExpandAcknowledgement(1, 0)

	if err != nil {
		t.Fatalf("expected expansion to succeed, got %v", err)
	}
	var shownChanged []int
	for _, view := range views {
		for _, line := range view.Lines {
			if line.Changed {
				shownChanged = append(shownChanged, line.Number)
			}
		}
	}
	for _, n := range []int{5, 6, 7, 8, 9} {
		if !containsInt(shownChanged, n) {
			t.Errorf("expected the expansion to show changed line %d, got %v", n, shownChanged)
		}
	}
}

func TestExpandingAnAcknowledgedBinaryReportsItHasNoLines(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{acknowledgingStep("logo.png")}
	session := sessionDerivingBoth(nil, []review.OpaqueChange{{File: "logo.png", Kind: review.OpaqueBinary, Detail: "binary file"}})
	mustPost(t, session, walkthrough)

	views, err := session.ExpandAcknowledgement(1, 0)

	if err != nil {
		t.Fatalf("expected expansion to succeed, got %v", err)
	}
	if len(views) != 1 || views[0].Problem == "" {
		t.Fatalf("expected one view explaining the binary cannot be shown, got %+v", views)
	}
}

func TestAFileClaimedByTwoAcknowledgementsIsRejected(t *testing.T) {
	walkthrough := validWalkthrough()
	walkthrough.Steps = []review.Step{
		acknowledgingStep("package-lock.json"),
		acknowledgingStep("package-lock.json"), // the same file, again
	}
	session := sessionDerivingBoth(changed("package-lock.json", 1, 5), nil)

	err := session.Post(walkthrough)

	assertRejected(t, err, review.RejectedMalformedStep)
	assertDetailContains(t, err, "package-lock.json")
}

func TestExpandingANonexistentAcknowledgementIsRejected(t *testing.T) {
	session := sessionDeriving(changed("src/fetch.ts", 20, 22))
	mustPost(t, session, validWalkthrough())

	_, err := session.ExpandAcknowledgement(1, 3) // Step 1 has no Acknowledgements

	assertRejected(t, err, review.RejectedNoSuchAcknowledgement)
}
