package tui

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/probertson/diff-by-numbers/internal/daemon"
)

// ackStep is a Step with one narrated line and one Acknowledgement over two
// files, so a test can walk from the Step's own code onto the Acknowledgement.
func ackStep() *daemon.StepWire {
	return &daemon.StepWire{
		Name: "Regenerate", Explanation: "x",
		Excerpts: []daemon.ExcerptWire{{File: "a.go", Side: "new", FirstLine: 1, LastLine: 1, Lines: []daemon.LineWire{
			{Number: 1, Text: "narrated", Side: "new", Changed: true},
		}}},
		Acknowledgements: []daemon.AcknowledgementWire{{
			Reason: "regenerated by the build",
			Entries: []daemon.AcknowledgedFileWire{
				{File: "gen.go", ChangedLines: 3, Change: "modified"},
				{File: "logo.png", Opaque: "binary", OpaqueDetail: "binary file", Change: "binary"},
			},
		}},
	}
}

// ackExpansion is what the daemon expands ackStep's Acknowledgement into: a
// unified edit of gen.go, then the binary it cannot show.
func ackExpansion() []daemon.ExcerptWire {
	return []daemon.ExcerptWire{
		{File: "gen.go", Side: "new", FirstLine: 2, LastLine: 3, Lines: []daemon.LineWire{
			{Number: 2, Text: "old generated", Side: "old", Changed: true},
			{Number: 2, Text: "new generated", Side: "new", Changed: true},
			{Number: 3, Text: "more generated", Side: "new", Changed: true},
		}},
		{File: "logo.png", Problem: "logo.png is an Opaque Change (binary file) with no lines to show"},
	}
}

func TestACollapsedAcknowledgementIsACursorStop(t *testing.T) {
	cur := newStepCursor(ackStep(), nil)

	cur.move(1)

	line := cur.lines[cur.cursor]
	if line.kind != kindStop || line.ack != 0 {
		t.Fatalf("expected the cursor to land on the Acknowledgement's stop, got %+v", line)
	}
}

func TestAnAcknowledgementOnlyStepStartsOnItsStop(t *testing.T) {
	step := ackStep()
	step.Excerpts = nil

	cur := newStepCursor(step, nil)
	out := renderStep(step, cur, map[string]bool{}, nil, 80, 40, false)

	if len(cur.lines) != 1 || cur.lines[0].kind != kindStop {
		t.Fatalf("expected a single stop to rest on, got %+v", cur.lines)
	}
	stop := lineWith(t, out, "Acknowledged")
	if !strings.Contains(stop, "▸") || !strings.Contains(stop, "regenerated by the build") || !strings.Contains(stop, "2 files") {
		t.Errorf("expected the stop to carry the caret, reason and file count, got %q", stop)
	}
	if !strings.Contains(out, "gen.go") || !strings.Contains(out, "logo.png") {
		t.Errorf("expected the collapsed manifest to name its files:\n%s", out)
	}
}

func TestAnExpandedAcknowledgementRendersInlineAsRealCode(t *testing.T) {
	step := ackStep()
	cur := newStepCursor(step, map[int][]daemon.ExcerptWire{0: ackExpansion()})

	out := renderStep(step, cur, map[string]bool{}, nil, 80, 40, false)

	for _, want := range []string{"narrated", "Acknowledged", "── gen.go", "old generated", "new generated", "── logo.png", "binary file"} {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in the pane:\n%s", want, out)
		}
	}
	if strings.Index(out, "old generated") > strings.Index(out, "new generated") {
		t.Error("expected the removal above its replacement")
	}
	if strings.Contains(out, "more not shown") {
		t.Error("an expansion is windowed, never truncated")
	}
}

func TestTheCursorSkipsAnOpaqueChangeInAnExpansion(t *testing.T) {
	step := ackStep()
	step.Acknowledgements = append(step.Acknowledgements, daemon.AcknowledgementWire{Reason: "second"})
	cur := newStepCursor(step, map[int][]daemon.ExcerptWire{0: ackExpansion()})
	cur.cursor = 4 // the last line of gen.go

	cur.move(1)

	if line := cur.lines[cur.cursor]; line.kind != kindStop || line.ack != 1 {
		t.Errorf("expected the cursor to pass the binary and land on the next stop, got %+v", line)
	}
}

func TestASelectionInAcknowledgedCodeNamesTheAcknowledgement(t *testing.T) {
	cur := newStepCursor(ackStep(), map[int][]daemon.ExcerptWire{0: ackExpansion()})
	cur.cursor = 2 // the removed row of gen.go

	cur.extend(1)
	run, ok := cur.selection()

	if !ok {
		t.Fatal("expected acknowledged code to be selectable")
	}
	if run.ack != 0 || run.excerpt != 0 || run.start != (rowRef{side: "old", line: 2}) || run.end != (rowRef{side: "new", line: 2}) {
		t.Errorf("unexpected run %+v", run)
	}
	body := anchorBody(run)
	if body["acknowledgement_index"] != 0 {
		t.Errorf("expected the anchor body to name the Acknowledgement, got %+v", body)
	}
}

func TestANarratedSelectionSendsNoAcknowledgement(t *testing.T) {
	cur := newStepCursor(ackStep(), nil)

	run, _ := cur.selection()

	if _, present := anchorBody(run)["acknowledgement_index"]; present {
		t.Error("expected a narrated selection to carry no Acknowledgement")
	}
}

func TestAStopCannotBeSelected(t *testing.T) {
	cur := newStepCursor(ackStep(), nil)
	cur.cursor = 1 // the stop

	if _, ok := cur.selection(); ok {
		t.Error("a stop is not code and cannot be anchored")
	}
}

func TestTheAcknowledgementHeaderStaysOnScreenInsideItsCode(t *testing.T) {
	var lines []daemon.LineWire
	for n := 1; n <= 60; n++ {
		lines = append(lines, daemon.LineWire{Number: n, Text: fmt.Sprintf("generated %d", n), Side: "new", Changed: true})
	}
	step := ackStep()
	expansion := map[int][]daemon.ExcerptWire{0: {{File: "gen.go", Side: "new", FirstLine: 1, LastLine: 60, Lines: lines}}}
	cur := newStepCursor(step, expansion)
	cur.cursor = len(cur.lines) - 1
	const height = 20

	out := renderStep(step, cur, map[string]bool{}, nil, 80, height, false)

	if got := lipgloss.Height(out); got > height {
		t.Errorf("the pane is %d rows, over the %d given", got, height)
	}
	sticky := strings.Index(out, "Acknowledged")
	file := strings.Index(out, "── gen.go")
	code := strings.Index(out, "generated 60")
	if sticky < 0 || file < 0 || code < 0 {
		t.Fatalf("expected the Acknowledgement and file headers above the code:\n%s", out)
	}
	if !(sticky < file && file < code) {
		t.Errorf("expected the Acknowledgement header above the file header above the code:\n%s", out)
	}
	if !strings.Contains(out, "more above") {
		t.Error("expected a 'more above' indicator deep inside the expansion")
	}
}

func TestACollapsedAcknowledgementCountsItsChangeRequests(t *testing.T) {
	step := ackStep()
	cur := newStepCursor(step, nil)

	out := renderStep(step, cur, map[string]bool{}, []int{1}, 80, 40, false)

	if !strings.Contains(lineWith(t, out, "Acknowledged"), "1 Change Request") {
		t.Errorf("expected the stop to count its Change Request:\n%s", out)
	}
}

func TestAckChangeRequestsCountsThoseRaisedInEachAcknowledgement(t *testing.T) {
	first := 0
	m := model{view: &daemon.ViewWire{Posted: true, Position: 1, Step: ackStep(), ChangeRequests: []daemon.ChangeRequestWire{
		{Step: 1, File: "gen.go", Acknowledgement: &first},
		{Step: 1, File: "gen.go"}, // the same file, but in the Step's own code
		{Step: 2, File: "gen.go", Acknowledgement: &first},
	}}}

	counts := m.ackChangeRequests()

	if len(counts) != 1 || counts[0] != 1 {
		t.Errorf("expected one Change Request raised in this Step's Acknowledgement, got %v", counts)
	}
}

// expandServer answers /expand with ackExpansion, counting the calls.
func expandServer(t *testing.T) *httptest.Server {
	t.Helper()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/expand/") {
			http.NotFound(w, r)
			return
		}
		json.NewEncoder(w).Encode(ackExpansion())
	}))
	t.Cleanup(server.Close)
	return server
}

func stepModel(t *testing.T, step *daemon.StepWire) model {
	t.Helper()
	m := model{
		client: client{base: expandServer(t).URL},
		mode:   modeReview,
		view:   &daemon.ViewWire{Posted: true, Position: 1, StepCount: 1, Step: step},
		width:  80, height: 40, ready: true,
	}
	m.syncCursor()
	return m
}

func press(m model, key string) model {
	var msg tea.KeyMsg
	switch key {
	case "down":
		msg = tea.KeyMsg{Type: tea.KeyDown}
	case "up":
		msg = tea.KeyMsg{Type: tea.KeyUp}
	default:
		msg = tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune(key)}
	}
	after, _ := m.Update(msg)
	return after.(model)
}

func TestXOnAStopExpandsItAndLandsInItsCode(t *testing.T) {
	m := press(stepModel(t, ackStep()), "down") // onto the stop

	m = press(m, "x")

	line := m.cursor.lines[m.cursor.cursor]
	if line.kind != kindCode || line.ack != 0 || line.number != 2 || line.side != "old" {
		t.Errorf("expected the cursor on the first row of the expansion, got %+v", line)
	}
}

func TestXInsideAcknowledgedCodeCollapsesItOntoItsStop(t *testing.T) {
	m := press(press(stepModel(t, ackStep()), "down"), "x")
	m = press(m, "down")

	m = press(m, "x")

	line := m.cursor.lines[m.cursor.cursor]
	if line.kind != kindStop || line.ack != 0 {
		t.Errorf("expected the cursor back on the stop, got %+v", line)
	}
	if len(m.cursor.lines) != 2 {
		t.Errorf("expected the expansion gone, got %d lines", len(m.cursor.lines))
	}
}

func TestSelectingOnAStopExplainsHowToReachTheCode(t *testing.T) {
	m := press(stepModel(t, ackStep()), "down")

	m = press(m, "v")

	if !strings.Contains(m.status, "expand with x") {
		t.Errorf("expected a hint to expand first, got %q", m.status)
	}
}

func TestAnEntirelyOpaqueAcknowledgementKeepsTheCursorOnItsStop(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode([]daemon.ExcerptWire{{File: "logo.png", Problem: "logo.png is an Opaque Change (binary file) with no lines to show"}})
	}))
	defer server.Close()
	step := ackStep()
	step.Excerpts = nil
	m := stepModel(t, step)
	m.client = client{base: server.URL}

	m = press(m, "x")

	if line := m.cursor.lines[m.cursor.cursor]; line.kind != kindStop {
		t.Errorf("expected the cursor to stay on the stop, got %+v", line)
	}
	if !m.cursor.isExpanded(0) {
		t.Error("expected the Acknowledgement to be expanded")
	}
}
